### ISSUE TITLE
Proportional payout for repaired slots

### ISSUE THREAD

**Issue by AuHau** [codex-storage/codex-contracts-eth#100]
Currently, when a slot is freed and another host repairs it, they receive the repair reward. Upon successfully completing the slot, they will receive the reward for the entire storage contract duration, not just a portion based on how long they filled the slot (e.g., from the time of slot repair).

Is this desirable? Could it pose a problem?

**Comment by dryajov** [comment]
>  Upon successfully completing the slot, they will receive the reward for the entire storage contract duration, not just a portion based on how long they filled the slot (e.g., from the time of slot repair).

Yes, this is a problem, the new node should receive only a portion of the rewards corresponding to the repair fee + the remainder of the contract duration.

**Comment by emizzle** [comment]
Definitely a problem. That would make repair very valuable, and would possibly exceed the collateral an SP has in an existing request, therefore potentially incentivising the SP to abandon the existing filled slot for the repair.
