### ISSUE TITLE
Payout based on actual time filling the slot

### ISSUE THREAD

**Issue by AuHau** [codex-storage/codex-contracts-eth#102]
Currently, if a node fills a slot and the request successfully finishes, it gets paid for the **entire request duration** regardless of when the node actually filled the slot. 

In the context of Slot Reservations, we proposed that changing this behavior to payment based on the actual time of slot filling would create a small incentive to fill the slot as soon as possible.

**Comment by emizzle** [comment]
Just a note, I believe this was meant to be in the original design, ie mutually exclusive to the slot reservations design. However, as you pointed out, it would act as an incentive for SPs to fill slots as quickly as possible negating the need for a fill reward in slot reservations.
