### ISSUE TITLE
Check that `maxSlotLoss` is not bigger then `slots`

### ISSUE THREAD

**Issue by AuHau** [codex-storage/codex-contracts-eth#139]
There should be this check in `fillSlot`: https://github.com/codex-storage/codex-contracts-eth/blob/master/contracts/Marketplace.sol#L113

**Comment by 0x-r4bbit** [comment]
Addressed in https://github.com/codex-storage/codex-contracts-eth/pull/140, however @AuHau I believe the check has to happen in `requestStorage` and not in `fillSlot`.

We don't want this incorrect state to enter the system in the first place.
