### ISSUE TITLE
Certora integration

### ISSUE THREAD

**Issue by emizzle** [codex-storage/codex-contracts-eth#53]
- [x] Write Application Properties document
- [x] Write Certora tests
- [x] Integrate Certora with tests into CI

**Comment by 0x-r4bbit** [comment]
@AuHau Would you mind adding @gravityBlast as an assignee as well? He's gonna help setting it up this week.

**Comment by 0x-r4bbit** [comment]
@emizzle the integration of Certora + some first certora rules have landed with #122 
So I think we can close this one?

I've created individual issues for individual rules for us to implement.
