### ISSUE TITLE
Reward address

### ISSUE THREAD

**Issue by AuHau** [codex-storage/codex-contracts-eth#71]
As Ethereum 2 validators have several addresses, maybe the Codex node could have a "reward address"?

**Comment by AuHau** [comment]
https://ethereum.org/en/staking/withdrawals/

**Comment by emizzle** [comment]
Provide payout/profit address on the `freeSlot` routine.

**Comment by emizzle** [comment]
Profits to reward address, but collateral gets returned to the address from which it came?

**Comment by AuHau** [comment]
> Profits to reward address, but collateral gets returned to the address from which it came?

Yes
